services:
  # Official LightRAG Server with Web UI and Knowledge Graph Visualization
  lightrag-server:
    container_name: lightrag-server
    image: ghcr.io/hkuds/lightrag:latest
    ports:
      - "9621:9621"  # LightRAG Web UI and API
    volumes:
      - ./lightrag-data/rag_storage:/app/data/rag_storage
      - ./lightrag-data/inputs:/app/data/inputs
      - ./lightrag-config.ini:/app/config.ini
      - ./lightrag.env:/app/.env
    env_file:
      - lightrag.env
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - lightrag-network

  # Neo4j for Graph Storage (Optional but recommended for visualization)
  neo4j:
    image: neo4j:5.13-community
    container_name: lightrag-neo4j
    ports:
      - "7474:7474"  # Neo4j Browser
      - "7687:7687"  # Bolt protocol
    environment:
      - NEO4J_AUTH=neo4j/lightragpassword123
      - NEO4J_PLUGINS=["apoc"]
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
    networks:
      - lightrag-network
    restart: unless-stopped

volumes:
  neo4j_data:
    driver: local
  neo4j_logs:
    driver: local

networks:
  lightrag-network:
    driver: bridge 